### ISSUE TITLE
How to use the Azure KeyVault SecretProvider with Managed service Identity

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.security#217]
**Description**
I am playing and digging around a bit with the Azure KeyVault SecretProvider (code that is now on t he master branch), and I'm wondering how I will be able to connect the SecretProvider to Azure KeyVault using Managed Service Identity.

I'm currently using a 1.4.0-alpha build and with that build, I'm able to connect to KeyVault using MSI like this:

```csharp
.ConfigureSecretStore((context, config, builder) =>
{
    builder.AddAzureKeyVaultWithManagedServiceIdentity(
                    securitySettings.KeyVault.KeyVaultUri, 
                    allowCaching: true,
                    mutateSecretName: secretName => secretName.Replace(":", "--"));
}
```

In the current version that is on master, it seems that this method has been marked as obsolete and you need to use the `AddAzureKeyVault
![image](https://user-images.githubusercontent.com/3605786/101094022-080b1580-35bc-11eb-8aee-66bd7c2ae901.png)

I don't have `clientId` however, I want to make use of Managed Service Identity.   
I see though that the `clientId` parameter of the proposed method is optional, 

![image](https://user-images.githubusercontent.com/3605786/101094280-6fc16080-35bc-11eb-9fbb-1e913f4b1385.png)

So I thought to give that a go.

![image](https://user-images.githubusercontent.com/3605786/101094390-a0a19580-35bc-11eb-9fe2-3a8421e027e9.png)

Unfortunately, this results in this exception:

```
Azure.Identity.AuthenticationFailedException : The ChainedTokenCredential failed to retrieve a token from the included credentials.
---- System.AggregateException : Multiple exceptions were encountered while attempting to authenticate. (ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found.) (EnvironmentCredential authentication unavailable. Environment variables are not fully configured.)
-------- Azure.Identity.CredentialUnavailableException : ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found.
-------- Azure.Identity.CredentialUnavailableException : EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
   at Arcus.Security.Core.CompositeSecretProvider.WithSecretStoreAsync[T](String secretName, Func`2 callRegisteredProvider) in C:\Dev\R_and_D\arcus\arcus.security\src\Arcus.Security.Core\CompositeSecretProvider.cs:line 215
   at Arcus.Security.Core.CompositeSecretProvider.GetSecretAsync(String secretName) in C:\Dev\R_and_D\arcus\arcus.security\src\Arcus.Security.Core\CompositeSecretProvider.cs:line 99
   at Arcus.Security.Tests.Integration.KeyVault.SecretStoreBuilderExtensionsTests.AddAzureKeyVault_WithManagedServiceIdentity_GetSecretSucceeds() in C:\Dev\R_and_D\arcus\arcus.security\src\Arcus.Security.Tests.Integration\KeyVault\SecretStoreBuilderExtensionsTests.cs:line 325
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----

----- Inner Stack Trace #1 (Azure.Identity.CredentialUnavailableException) -----
   at Azure.Identity.ManagedIdentityClient.AuthenticateAsync(String[] scopes, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.ChainedTokenCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
----- Inner Stack Trace #2 (Azure.Identity.CredentialUnavailableException) -----
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
   at Azure.Identity.EnvironmentCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.EnvironmentCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.ChainedTokenCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
````

*Give more information about your doubt*

Am I doing something wrong ?
It seems that all ` AddAzureKeyVaultWithManagedServiceIdentity` [methods are marked as obsolete](https://github.com/arcus-azure/arcus.security/blob/941d8c6109a36e9059afd739411a92f55c2fea46/src/Arcus.Security.Providers.AzureKeyVault/Extensions/SecretStoreBuilderExtensions.cs#L242) ?

How can I use Azure KeyVault SecretProvider with MSI ?
I've looked at the [preview documentation](https://github.com/arcus-azure/arcus.security/blob/master/docs/preview/features/secret-store/provider/key-vault.md) but it doesn't seem to be updated yet.

**Comment by tomkerkhove** [comment]
Hm this should be working actually. Where did you run this? In Azure, a container or locally?

If it's locally then that's normal because that required the environment variables to be in place or use `` and pass [`DefaultAzureCredential`](https://github.com/Azure/azure-sdk-for-net/tree/68d7fd61aec3f7845a835c7353c69fd9fc877e21/sdk/identity/Azure.Identity#defaultazurecredential).

We don't do that by default for now.

To give some context, we're reshuffling things to standardize on [`Azure.Identity`](https://github.com/Azure/azure-sdk-for-net/tree/68d7fd61aec3f7845a835c7353c69fd9fc877e21/sdk/identity/Azure.Identity) instead of our own approach as that seems to be the long-term future.

References:
- Old deprecated approach - https://github.com/arcus-azure/arcus.security/blob/master/src/Arcus.Security.Providers.AzureKeyVault/Extensions/SecretStoreBuilderExtensions.cs#L243 
- New - https://github.com/arcus-azure/arcus.security/blob/master/src/Arcus.Security.Providers.AzureKeyVault/Extensions/SecretStoreBuilderExtensions.cs#L402

**Comment by fgheysels** [comment]
I ran it locally.
Do you mean pass '' as clientId ?
How can I pass DefaultAzureCredential ?  There doesn't seem to be a parameter which accepts that.

**Comment by tomkerkhove** [comment]
If it was locally then there are 2 options:
- Use [`AddAzureKeyVault`](https://github.com/arcus-azure/arcus.security/blob/master/src/Arcus.Security.Providers.AzureKeyVault/Extensions/SecretStoreBuilderExtensions.cs#L809) and pass `DefaultAzureCredential`
- We change our approach to use [`DefaultAzureCredential`](https://github.com/Azure/azure-sdk-for-net/tree/68d7fd61aec3f7845a835c7353c69fd9fc877e21/sdk/identity/Azure.Identity#defaultazurecredential)

Not sure if we want to use default because it is more than MI, but I would get both sides

**Comment by fgheysels** [comment]
I ran it locally and tried using AddAzureKeyVault, which works locally, but is a bit cumbersome (lots of parameters required and not that developer-friendly).  
So I think it would be nice if there would be a way to be able to use AddAzureKeyVaultWithManagedIdentity that just works both locally and in the cloud.

**Comment by tomkerkhove** [comment]
@stijnmoreels lets use DefaultAzureCredential for our Managed identity extension as this would only open up to VS and CLI which is secure

**Comment by stijnmoreels** [comment]
Hmm, this can be closed then? @tomkerkhove @fgheysels
